<?php

namespace AppBundle\Repository;

/**
 * SicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SicRepository extends \Doctrine\ORM\EntityRepository
{
}
